apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bankapp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==        # root
  MYSQL_DATABASE: YmFua2Ri            # bankdb
  MYSQL_USER: YmFua3VzZXI=            # bankuser
  MYSQL_PASSWORD: YmFua3Bhc3M=        # bankpass